import React from 'react';
import {AbsoluteFill,Audio,Composition,Img,Sequence,interpolate,registerRoot,staticFile,useCurrentFrame} from 'remotion';
const C='#6ee7bd';
const ease=(f:number,a=0,b=30)=>{const t=interpolate(f,[a,b],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp'});return 1-Math.pow(1-t,3)};
const Shot=({children}:{children:React.ReactNode})=>{const f=useCurrentFrame();return <AbsoluteFill style={{opacity:ease(f,0,16),transform:`translateY(${(1-ease(f))*22}px)`}}>{children}</AbsoluteFill>};
const Text=({n,title,desc}:{n:string,title:string,desc:string})=><div style={{position:'absolute',left:105,top:230,width:700}}><div style={{fontSize:22,color:C,letterSpacing:4,marginBottom:30}}>{n}</div><div style={{fontSize:68,fontWeight:650,lineHeight:1.27,whiteSpace:'pre-line',letterSpacing:-2}}>{title}</div><div style={{fontSize:28,color:'#a1afbf',lineHeight:1.8,marginTop:28,whiteSpace:'pre-line'}}>{desc}</div></div>;
function Phone({src,x=1260,y=180,w=340}:{src:string,x?:number,y?:number,w?:number}){return <div style={{position:'absolute',left:x,top:y,width:w,height:w*2+38,padding:10,paddingTop:24,borderRadius:45,background:'linear-gradient(140deg,#61717c,#141b24 22%,#344450)',boxShadow:'0 36px 90px #0009',border:'2px solid #758391',boxSizing:'content-box'}}><div style={{position:'absolute',top:9,left:'43%',width:'14%',height:5,borderRadius:10,background:'#070b10'}}/><Img src={staticFile('textures/'+src+'.png')} style={{width:w,height:w*2,borderRadius:28,objectFit:'cover'}}/><div style={{margin:'9px auto 0',width:100,height:4,borderRadius:9,background:'#90a2b2'}}/></div>}
function Laptop({src='companion',x=640,y=320,w=1100}:{src?:string,x?:number,y?:number,w?:number}){return <div style={{position:'absolute',left:x,top:y,width:w}}><div style={{background:'linear-gradient(140deg,#586875,#151c25)',padding:14,paddingTop:23,borderRadius:'25px 25px 10px 10px',border:'2px solid #586574',boxShadow:'0 40px 90px #0008'}}><div style={{position:'absolute',top:8,left:'50%',height:5,width:5,borderRadius:10,background:'#748998'}}/><Img src={staticFile('textures/'+src+'.png')} style={{width:'100%',height:w*.59,objectFit:'cover',objectPosition:'top',display:'block',borderRadius:5}}/></div><div style={{width:'110%',height:23,marginLeft:'-5%',background:'linear-gradient(#9aa9b5,#35434f)',borderRadius:'3px 3px 50% 50%'}}/></div>}
const Badge=({text,x,y}:{text:string,x:number,y:number})=><div style={{position:'absolute',left:x,top:y,padding:'12px 24px',border:'1px solid #365749',borderRadius:30,color:C,fontSize:24,background:'#10241eee'}}>{text}</div>;
const Tap=({x,y,at}:{x:number,y:number,at:number})=>{const f=useCurrentFrame();const t=interpolate(f,[at,at+22],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp'});return f<at||f>at+22?null:<div style={{position:'absolute',left:x-30,top:y-30,width:60,height:60,border:`3px solid ${C}`,background:'#6ee7bd33',borderRadius:100,transform:`scale(${.5+t})`,opacity:1-t}}/>};
function Intro(){return <Shot><div style={{position:'absolute',left:105,top:175,fontSize:68,fontWeight:650,lineHeight:1.18}}>Your interview on the computer.<br/><span style={{color:C}}>Your guidance on the phone.</span></div><Laptop x={175} y={390} w={920}/><Phone src="phone-answer" x={1370} y={225} w={335}/><Badge text="Companion runs on your computer" x={330} y={1010}/><Badge text="View guidance on your phone" x={1330} y={970}/></Shot>}
function Setup(){const f=useCurrentFrame();return <Shot><Text n="01 / SET UP YOUR COMPUTER" title={'Install and open\nthe companion app'} desc={'Allow microphone and screen access.\nFind the connection code shown in the app.'}/><Laptop x={840} y={260} w={930}/><div style={{position:'absolute',left:120,top:730,display:'flex',alignItems:'center',gap:24}}><Img src={staticFile('icon.png')} style={{width:78,height:78,borderRadius:18}}/><span style={{fontSize:25,color:C}}>OfferSteady · Desktop Companion</span></div><div style={{position:'absolute',left:1310,top:642,width:190,height:50,border:`2px solid ${C}`,borderRadius:12,opacity:ease(f,80,100)}}/></Shot>}
function Connect(){const f=useCurrentFrame();const connected=f>=175;return <Shot><Text n="02 / CONNECT THIS INTERVIEW" title={'Open the web app\non your phone'} desc={'Sign in with the same account.\nEnter the computer connection code.'}/><div style={{position:'absolute',left:110,top:690,width:580,height:145,overflow:'hidden',border:'1px solid #406052',borderRadius:20,background:'#0e151e'}}><Img src={staticFile('textures/companion.png')} style={{position:'absolute',width:1400,left:-700,top:-555}}/></div><Phone src="connect" x={1255} y={160} w={365}/><div style={{position:'absolute',left:1287,top:505,width:300,padding:'20px 18px',border:'1px solid #35594d',borderRadius:16,background:'#101c25f5',boxShadow:'0 18px 45px #0008'}}><div style={{fontSize:15,color:'#a5b2c2',marginBottom:12}}>Connect Desktop Companion</div><div style={{display:'flex',gap:10}}><div style={{flex:1,padding:'13px 12px',border:'1px solid #344353',borderRadius:10,color:C,fontSize:23,fontWeight:800,letterSpacing:5}}>628391</div><div style={{padding:'15px 12px',borderRadius:10,background:connected?'#153a30':C,color:connected?C:'#07110e',fontSize:14,fontWeight:700}}>{connected?'Connected':'Verify'}</div></div><div style={{marginTop:12,color:connected?C:'#8796a8',fontSize:13}}>{connected?'This session is ready to start.':'Enter the code shown on your computer.'}</div></div><Tap x={1545} y={560} at={157}/><Badge text={connected?'Device connected for this session':'Use the same connection code'} x={780} y={550}/></Shot>}
function Question(){const f=useCurrentFrame();return <Shot><Text n="03 / START YOUR INTERVIEW" title={'Questions on the computer.\nGuidance on your phone.'} desc={'Follow the live conversation.\nTap Quick Answer whenever you need help.'}/><Phone src={f<215?'phone-question':'phone-answer'} x={1240} y={155} w={365}/><Laptop x={130} y={620} w={620}/><Badge text="Keep the companion running" x={760} y={775}/><Tap x={1513} y={884} at={200}/></Shot>}
function Answer(){return <Shot><Text n="04 / READ YOUR GUIDANCE" title={'Get the key idea first.\nThen add the detail.'} desc={'Read the quick and detailed answer.\nGuidance uses the materials selected for this session.'}/><Phone src="phone-answer" x={1340} y={155} w={365}/><div style={{position:'absolute',left:108,top:650,width:980,height:280,border:`1px solid #416657`,borderRadius:24,overflow:'hidden',boxShadow:'0 28px 80px #0006'}}><Img src={staticFile('textures/phone-answer.png')} style={{position:'absolute',width:1020,left:-20,top:-1150}}/></div></Shot>}
function Tablet(){return <Shot><Text n="ANOTHER VIEW / TABLET" title={'Want more room?\nUse a tablet.'} desc={'Open the interview page in your tablet browser.\nChoose the screen that works for you.'}/><div style={{position:'absolute',left:840,top:300,width:940,padding:18,borderRadius:35,background:'linear-gradient(130deg,#6c7f8b,#17212b)',boxShadow:'0 30px 80px #0008',border:'2px solid #637888'}}><Img src={staticFile('textures/tablet.png')} style={{width:'100%',display:'block',borderRadius:18}}/></div></Shot>}
function Desktop(){return <Shot><Text n="ANOTHER VIEW / COMPUTER" title={'Prefer your computer?\nUse the web app there.'} desc={'Run the companion and view the conversation\nand guidance in the web app.'}/><Laptop src="desktop" x={820} y={305} w={970}/></Shot>}
function End(){const f=useCurrentFrame();return <Shot><div style={{position:'absolute',inset:0,display:'flex',flexDirection:'column',alignItems:'center',justifyContent:'center',transform:`scale(${.98+.02*ease(f,0,35)})`}}><Img src={staticFile('icon.png')} style={{width:106,height:106,borderRadius:25,marginBottom:28}}/><div style={{fontSize:46,fontWeight:600}}>OfferSteady</div><div style={{fontSize:72,fontWeight:650,marginTop:30}}>The computer runs it. <span style={{color:C}}>You choose where to view it.</span></div><div style={{fontSize:27,color:'#a1afbf',marginTop:34}}>Phone · Tablet · Computer Web App</div></div></Shot>}
const scenes=[{s:0,d:5,C:Intro},{s:5,d:7,C:Setup},{s:12,d:8,C:Connect},{s:20,d:9,C:Question},{s:29,d:7,C:Answer},{s:36,d:5,C:Tablet},{s:41,d:4,C:Desktop},{s:45,d:4,C:End}];
function Film({bgm=true}:{bgm?:boolean}){const f=useCurrentFrame();return <AbsoluteFill style={{background:'radial-gradient(ellipse at 78% 42%,#183139 0%,#101923 34%,#080d14 75%)',color:'#edf2f8',fontFamily:'Inter, "Helvetica Neue", Arial, sans-serif'}}><div style={{position:'absolute',left:104,top:65,display:'flex',alignItems:'center',gap:15}}><Img src={staticFile('icon.png')} style={{height:34,width:34,borderRadius:9}}/><span style={{fontSize:22,fontWeight:600}}>OfferSteady</span><span style={{fontSize:18,color:'#8395a7',marginLeft:20}}>Cross-device walkthrough</span></div><div style={{position:'absolute',right:100,top:74,fontSize:17,color:'#8193a5'}}>Real interface · Synthetic example · Edited flow</div>{scenes.map(s=><Sequence key={s.s} from={s.s*30} durationInFrames={s.d*30}><s.C/></Sequence>)}<div style={{position:'absolute',left:0,bottom:0,width:`${f/1470*100}%`,height:3,background:C}}/>{bgm?<Audio src={staticFile('audio/bgm-source.mp3')} volume={frame=>.14*Math.min(1,frame/45,(1470-frame)/60)} />:null}</AbsoluteFill>}
registerRoot(()=> <Composition id="GlobalDeviceStory" component={Film} width={1920} height={1080} fps={30} durationInFrames={1470} defaultProps={{bgm:true}}/>);
