import type { GuideContent } from "@offersteady/protocol";
export const guideContent: GuideContent = { version: "1.1.0", locale: "zh-CN", chapters: [
  { id: "quick-start", title: "快速开始", keywords: ["开始", "新用户", "200点", "空资料"], summary: "从登录、资料、设备到开始面试。", sections: [{ id: "steps", title: "五步开始", paragraphs: ["使用手机号验证码登录或注册。", "在简历、职位 JD、知识库三个分区按需维护资料。", "点击继续面试，在准备页选择本场资料，也可以明确选择为空。", "下载对应系统和芯片的伴随程序；本地端会负责检查收音、系统音频和问题检测。", "确认本场资料后即可开始面试；音频和截图在实际使用时单独授权或确认。"] }] },
  { id: "account-library", title: "账号与面试资料", keywords: ["短信", "登录", "资料库", "简历", "JD", "索引", "Token"], summary: "了解账号绑定、三类资料管理和索引扣点。", sections: [{ id: "sms", title: "短信账号", paragraphs: ["手机号验证码用于创建或登录面试稳账号。同一个手机号对应同一个账号，验证码只用于本次登录验证。"] }, { id: "library", title: "简历、职位 JD 与知识库", paragraphs: ["资料页按简历、职位 JD 和知识库分区。新增资料不会自动授权给面试，应在准备页逐场选择。空知识库免费；知识材料按服务端 Token 报价，最低 20 点、每 5,000 Token 20 点，成功建立索引后才结算。"] }] },
  { id: "desktop", title: "Windows 与 macOS", keywords: ["Windows", "macOS", "安装", "权限", "芯片"], summary: "选择安装包、授权收音并处理能力降级。", sections: [{ id: "windows", title: "Windows 安装", paragraphs: ["在设置的系统信息中确认 x64 架构，只下载标记为已验证的版本。"] }, { id: "macos", title: "macOS 安装", paragraphs: ["在关于本机中确认 Apple Silicon 或 Intel，并完成麦克风与系统音频授权。"] }, { id: "troubleshooting", title: "设备故障", paragraphs: ["系统音频不可用时，可继续使用麦克风、手动输入和截图。"] }] },
  { id: "live", title: "面试现场与截图题", keywords: ["面试", "双声道", "截图", "手动输入", "终止回答"], summary: "理解双角色实时对话、回答控制和截图回答。", sections: [{ id: "speaker", title: "对话与回答", paragraphs: ["桌面端左侧显示实时对话，左侧下方保留手动问题输入；右侧显示回答，右侧下方放置快答和截屏回答，可拖动中间分隔条调整宽度；手机按对话、输入、回答、操作顺序展示。本地麦克风或耳机固定显示为“我”，系统音频固定显示为“面试官”；来源无法区分时会停止自动回答并提示手动提问。", "回答生成期间可以点击“终止回答”。终止只停止当前回答，不会停止面试、收音或后续问题；开始面试和结束面试位于页面右上角。"] }, { id: "screenshot", title: "截图与手动提问", paragraphs: ["快答优先读取左侧手动输入；未输入时会自动整理候选人最近一次发言之后的面试官问题，再生成回答。截屏回答会立即发起当前屏幕截取，不需要先上传本地图片；失败或取消后可重新发起，不会静默保存未确认的截屏。"] }] },
  { id: "billing", title: "积分、会员与支付", keywords: ["积分", "会员", "兑换码", "支付", "退款", "未到账", "支付未到账", "知识材料"], summary: "选择套餐、兑换积分并处理支付确认。", sections: [{ id: "plans", title: "选择使用方式", paragraphs: ["低频使用可以买积分，高频面试可以选择按天会员。知识材料最低 20 点、每 5,000 Token 20 点；15 天和 30 天会员每个生效周期包含 2 份知识材料额度。"] }, { id: "redemption", title: "兑换积分", paragraphs: ["在积分页输入一次性兑换码。兑换成功后点数进入当前账号的同一钱包；兑换不是支付，不需要交易单号或付款截图。", "兑换码相当于敏感凭证，不要发到公开群聊或截图中。不可用时检查输入并联系客服，但不要发送完整兑换码。"] }, { id: "payment", title: "官方支付", paragraphs: ["微信和支付宝使用订单专属动态支付动作。页面返回不代表到账，需等待服务端确认。"] }, { id: "delayed", title: "支付未确认", paragraphs: ["不要重复付款。刷新订单状态，长时间未确认时携带订单号联系客服。"] }] },
  { id: "privacy-support", title: "隐私、故障与客服", keywords: ["隐私", "删除", "客服", "微信", "邮箱", "故障"], summary: "数据控制、故障排查和人工帮助。", sections: [{ id: "privacy", title: "数据与隐私", paragraphs: ["原始音频默认不保存，资料和记录提供删除入口。"] }, { id: "support", title: "联系客服", paragraphs: ["需要人工帮助时，可通过页面下方的客服微信或联系邮箱咨询。请勿发送密码、验证码或完整身份资料。"] }] },
] };
export const safeGuideContent = (content: GuideContent) => { const unsafe = /<script|<iframe|javascript:/i; if (content.chapters.some(chapter => unsafe.test(JSON.stringify(chapter)))) throw new Error("unsafe-guide-content"); return content; };
