import { useMemo, useState } from "react";
import type { BillingSupportConfig } from "@offersteady/protocol";
import { Link, useLocation } from "react-router-dom";
import { guideContent, safeGuideContent } from "./guide-content";
import { routes } from "./routes";

export function GuidePage({ support }: { readonly support: BillingSupportConfig }) {
  const location = useLocation(); const [query, setQuery] = useState(""); const [copied, setCopied] = useState(false); const content = safeGuideContent(guideContent);
  const matches = useMemo(() => { const normalized = query.trim().toLowerCase(); if (!normalized) return content.chapters; return content.chapters.filter(chapter => `${chapter.title} ${chapter.summary} ${chapter.keywords.join(" ")} ${JSON.stringify(chapter.sections)}`.toLowerCase().includes(normalized)); }, [content.chapters, query]);
  const initial = location.hash.slice(1).split("/")[0]; const [activeId, setActiveId] = useState(content.chapters.some(item => item.id === initial) ? initial : content.chapters[0]!.id); const active = content.chapters.find(item => item.id === activeId) ?? content.chapters[0]!; const index = content.chapters.indexOf(active);
  const choose = (id: string) => { setActiveId(id); window.history.replaceState({}, "", `${routes.guide}#${id}`); };
  return <main className="app-page guide-page"><header className="page-header"><div><span className="kicker">USER GUIDE · v{content.version}</span><h1>使用说明</h1><p>从第一次登录到面试现场，按步骤找到需要的说明。</p></div><Link className="button primary" to={routes.app}>返回面试首页</Link></header><label className="guide-search"><span>搜索使用说明</span><input value={query} onChange={event => setQuery(event.target.value)} placeholder="例如：Windows、支付未到账、截图题" /></label><div className="guide-layout"><aside className="panel guide-toc" aria-label="使用说明目录">{matches.length ? matches.map(chapter => <button key={chapter.id} className={chapter.id === active.id ? "active" : ""} onClick={() => choose(chapter.id)}><strong>{chapter.title}</strong><small>{chapter.summary}</small></button>) : <p>没有找到相关说明，请尝试更短的关键词。</p>}</aside><article className="panel guide-article"><span className="guide-index">{String(index + 1).padStart(2, "0")} / {String(content.chapters.length).padStart(2, "0")}</span><h2>{active.title}</h2><p className="guide-summary">{active.summary}</p>{active.sections.map(section => <section id={`${active.id}/${section.id}`} key={section.id}><h3>{section.title}</h3>{section.paragraphs.map(paragraph => <p key={paragraph}>{paragraph}</p>)}</section>)}<nav className="guide-pager" aria-label="章节翻页"><button disabled={index === 0} onClick={() => choose(content.chapters[index - 1]!.id)}>← 上一章</button><button disabled={index === content.chapters.length - 1} onClick={() => choose(content.chapters[index + 1]!.id)}>下一章 →</button></nav></article></div><section className="guide-support"><div><span className="kicker">NEED MORE HELP?</span><h2>还没有解决？联系我们</h2><p>咨询订单时提供订单号即可，请勿发送密码、验证码或完整身份资料。</p></div><div className="support-contacts"><article><small>客服微信</small><strong>{support.wechatId}</strong><button type="button" onClick={() => { void navigator.clipboard?.writeText(support.wechatId); setCopied(true); }}>{copied ? "已复制" : "复制微信号"}</button></article><article><small>联系邮箱</small><strong>{support.email}</strong><a href={`mailto:${support.email}`}>发送邮件</a></article></div></section></main>;
}
