import type { KnowledgeCollection, KnowledgeDocumentStatus, KnowledgeDocumentVersion, KnowledgeFileKind, KnowledgeIndexQuote, KnowledgeIndexUsage } from "@offersteady/protocol";
import { BillingService } from "./billing-service.js";

const allowedKinds = new Set<KnowledgeFileKind>(["pdf", "docx", "txt", "md"]);
const QUOTE_TTL_MS = 15 * 60_000;
export interface TokenizerAdapter { readonly version: string; count(normalizedText: string): number; }
export const syntheticTokenizer: TokenizerAdapter = { version: "synthetic-v1", count: text => Math.max(0, Math.ceil(Array.from(text).length / 4)) };
export const knowledgeIndexPoints = (tokenCount: number, minimumPoints = 200, pointsPer1000 = 20) => tokenCount <= 0 ? 0 : Math.max(minimumPoints, Math.ceil(tokenCount / 1000) * pointsPer1000);
export class KnowledgeLibraryError extends Error { constructor(readonly code: "forbidden" | "not-found" | "invalid-file" | "invalid-state" | "quote-expired" | "quote-changed", message: string) { super(message); } }

export class KnowledgeLibraryService {
  private collections = new Map<string, KnowledgeCollection>();
  private documents = new Map<string, KnowledgeDocumentVersion>();
  private quotes = new Map<string, KnowledgeIndexQuote>();
  private usages = new Map<string, KnowledgeIndexUsage>();
  private counter = 0;
  constructor(private readonly billing: BillingService, private readonly tokenizer: TokenizerAdapter = syntheticTokenizer) {}

  createCollection(ownerUserId: string, name: string, nowMs = Date.now()) { const clean = name.trim(); if (!clean) throw new KnowledgeLibraryError("invalid-state", "资料库名称不能为空"); if (this.listCollections(ownerUserId).some(item => item.name === clean)) throw new KnowledgeLibraryError("invalid-state", "资料库名称已存在"); const value: KnowledgeCollection = { id: `collection-${++this.counter}`, ownerUserId, name: clean, createdAtMs: nowMs, updatedAtMs: nowMs }; this.collections.set(value.id, value); return value; }
  listCollections(ownerUserId: string) { return [...this.collections.values()].filter(item => item.ownerUserId === ownerUserId && !item.deletedAtMs); }
  renameCollection(ownerUserId: string, id: string, name: string, nowMs = Date.now()) { const value = this.collection(ownerUserId, id); const next = { ...value, name: name.trim(), updatedAtMs: nowMs }; this.collections.set(id, next); return next; }
  deleteCollection(ownerUserId: string, id: string, nowMs = Date.now()) { const value = this.collection(ownerUserId, id); if (value.deletedAtMs) return value; const documents = this.listDocuments(ownerUserId, id); const next = { ...value, deletedAtMs: nowMs, updatedAtMs: nowMs }; this.collections.set(id, next); documents.forEach(item => this.deleteDocument(ownerUserId, item.id, nowMs)); return next; }
  addDocument(ownerUserId: string, collectionId: string, input: { displayName: string; fileKind: KnowledgeFileKind; sizeBytes: number; pageCount?: number; contentFingerprint: string }, nowMs = Date.now()) { this.collection(ownerUserId, collectionId); if (!allowedKinds.has(input.fileKind) || input.sizeBytes <= 0 || input.sizeBytes > 50 * 1024 * 1024) throw new KnowledgeLibraryError("invalid-file", "文件类型或大小不受支持"); const existing = this.listDocuments(ownerUserId, collectionId).find(item => item.contentFingerprint === input.contentFingerprint && item.status !== "deleted"); if (existing) return existing; const prior = this.listDocuments(ownerUserId, collectionId).filter(item => item.displayName === input.displayName); const value: KnowledgeDocumentVersion = { id: `document-${++this.counter}`, collectionId, ownerUserId, displayName: input.displayName, fileKind: input.fileKind, sizeBytes: input.sizeBytes, ...(input.pageCount ? { pageCount: input.pageCount } : {}), contentFingerprint: input.contentFingerprint, version: prior.length + 1, status: "pending", createdAtMs: nowMs }; this.documents.set(value.id, value); return value; }
  listDocuments(ownerUserId: string, collectionId: string) { this.collection(ownerUserId, collectionId); return [...this.documents.values()].filter(item => item.ownerUserId === ownerUserId && item.collectionId === collectionId && item.status !== "deleted"); }

  quoteIndex(ownerUserId: string, documentId: string, normalizedText: string, nowMs = Date.now()): KnowledgeIndexQuote {
    const doc = this.document(ownerUserId, documentId); const clean = normalizedText.replace(/\s+/g, " ").trim(); const tokenCount = this.tokenizer.count(clean);
    if (!clean || tokenCount <= 0) throw new KnowledgeLibraryError("invalid-file", "资料中没有可索引文本");
    const allowance = this.billing.knowledgeAllowance(ownerUserId, nowMs); const source = allowance && allowance.remaining > 0 ? "pass_allowance" as const : "points" as const;
    const pointCost = knowledgeIndexPoints(tokenCount, this.billing.rates.knowledgeIndexMinimumPoints, this.billing.rates.knowledgeIndexPointsPer1000Tokens);
    const quote: KnowledgeIndexQuote = { quoteId: `knowledge-quote-${++this.counter}`, documentVersionId: doc.id, contentFingerprint: doc.contentFingerprint, tokenCount, billableUnits: Math.ceil(tokenCount / 1000), pointCost: source === "pass_allowance" ? 0 : pointCost, entitlementSource: source, allowanceRemaining: allowance?.remaining ?? 0, catalogVersion: this.billing.rates.catalogVersion, tokenizerVersion: this.tokenizer.version, createdAtMs: nowMs, expiresAtMs: nowMs + QUOTE_TTL_MS, requiresConfirmation: true, projectedBalance: this.billing.balance(ownerUserId) - (source === "points" ? pointCost : 0) };
    this.quotes.set(quote.quoteId, quote); return quote;
  }
  createLegacyQuote(ownerUserId: string, documentId: string, points = 20, nowMs = Date.now()) { const doc = this.document(ownerUserId, documentId); const quote: KnowledgeIndexQuote = { quoteId: `legacy-quote-${++this.counter}`, documentVersionId: doc.id, contentFingerprint: doc.contentFingerprint, tokenCount: 0, billableUnits: 0, pointCost: points, entitlementSource: "points", allowanceRemaining: 0, catalogVersion: 2, tokenizerVersion: "legacy-size-tier", createdAtMs: nowMs, expiresAtMs: nowMs + QUOTE_TTL_MS, requiresConfirmation: true, projectedBalance: this.billing.balance(ownerUserId) - points }; this.quotes.set(quote.quoteId, quote); return quote; }
  startIndex(ownerUserId: string, quoteId: string, usageId: string, nowMs = Date.now()) { const existing = this.usages.get(usageId); if (existing) return existing; const quote = this.quote(ownerUserId, quoteId); const doc = this.document(ownerUserId, quote.documentVersionId); if (quote.expiresAtMs <= nowMs) throw new KnowledgeLibraryError("quote-expired", "报价已过期"); if (quote.contentFingerprint !== doc.contentFingerprint) throw new KnowledgeLibraryError("quote-changed", "资料内容已变化，请重新报价"); if (quote.catalogVersion !== this.billing.rates.catalogVersion && quote.catalogVersion !== 2) throw new KnowledgeLibraryError("quote-changed", "费率目录已变化，请重新报价"); if (doc.status !== "pending" && doc.status !== "failed") throw new KnowledgeLibraryError("invalid-state", "资料当前不能建立索引"); const charge = this.billing.reserveUsage(ownerUserId, usageId, "knowledge_index", nowMs, doc.id, quote.pointCost, { quoteId, tokenCount: quote.tokenCount, tokenizerVersion: quote.tokenizerVersion }); const usage: KnowledgeIndexUsage = { id: usageId, userId: ownerUserId, documentVersionId: doc.id, points: charge.points, quoteId, tokenCount: quote.tokenCount, source: charge.source === "pass_allowance" ? "pass_allowance" : "points", catalogVersion: quote.catalogVersion, tokenizerVersion: quote.tokenizerVersion, status: "processing", createdAtMs: nowMs }; this.usages.set(usageId, usage); this.documents.set(doc.id, { ...doc, status: "processing" }); return usage; }
  completeIndex(ownerUserId: string, usageId: string, safeSummary: string, nowMs = Date.now()) { const usage = this.userUsage(ownerUserId, usageId); if (usage.status === "settled") return usage; this.billing.settleUsage(usageId, nowMs); const doc = this.document(ownerUserId, usage.documentVersionId); this.documents.set(doc.id, { ...doc, status: "ready", safeSummary }); const next = { ...usage, status: "settled" as const }; this.usages.set(usageId, next); return next; }
  failIndex(ownerUserId: string, usageId: string, nowMs = Date.now()) { const usage = this.userUsage(ownerUserId, usageId); if (usage.status === "released") return usage; this.billing.releaseUsage(usageId, nowMs); const doc = this.document(ownerUserId, usage.documentVersionId); this.documents.set(doc.id, { ...doc, status: "failed" }); const next = { ...usage, status: "released" as const }; this.usages.set(usageId, next); return next; }
  setDocumentStatus(ownerUserId: string, documentId: string, status: KnowledgeDocumentStatus) { const doc = this.document(ownerUserId, documentId); const next = { ...doc, status }; this.documents.set(documentId, next); return next; }
  deleteDocument(ownerUserId: string, documentId: string, nowMs = Date.now()) { const doc = this.document(ownerUserId, documentId); const { safeSummary: _removed, ...minimal } = doc; const next = { ...minimal, status: "deleted" as const, deletedAtMs: nowMs }; this.documents.set(documentId, next); return next; }
  historicalLabel(ownerUserId: string, documentId: string) { const doc = this.document(ownerUserId, documentId); return { displayName: doc.displayName, version: `v${doc.version}`, deleted: doc.status === "deleted" }; }
  private quote(userId: string, id: string) { const value = this.quotes.get(id); if (!value) throw new KnowledgeLibraryError("not-found", "报价不存在"); this.document(userId, value.documentVersionId); return value; }
  private collection(userId: string, id: string) { const value = this.collections.get(id); if (!value) throw new KnowledgeLibraryError("not-found", "资料库不存在"); if (value.ownerUserId !== userId) throw new KnowledgeLibraryError("forbidden", "无权访问资料库"); return value; }
  private document(userId: string, id: string) { const value = this.documents.get(id); if (!value) throw new KnowledgeLibraryError("not-found", "资料不存在"); if (value.ownerUserId !== userId) throw new KnowledgeLibraryError("forbidden", "无权访问资料"); return value; }
  private userUsage(userId: string, id: string) { const value = this.usages.get(id); if (!value) throw new KnowledgeLibraryError("not-found", "索引任务不存在"); if (value.userId !== userId) throw new KnowledgeLibraryError("forbidden", "无权访问索引任务"); return value; }
}
