import type { BillingProduct, OfficialCheckoutAction, OfficialCheckoutOrder, PaymentChannel, VerifiedPaymentNotification } from "@offersteady/protocol";
import { BillingService } from "./billing-service.js";

export interface OfficialPaymentProviderAdapter {
  create(input: { orderId: string; amountCents: number; currency: "CNY"; description: string }): Promise<OfficialCheckoutAction>;
  query(orderId: string): Promise<"pending" | "paid" | "failed" | "closed">;
  verifyNotification(payload: unknown): Promise<VerifiedPaymentNotification>;
  close(orderId: string): Promise<void>;
  refund(orderId: string, amountCents: number): Promise<"pending" | "refunded" | "failed">;
}
export class OfficialPaymentError extends Error { constructor(readonly code: "not-found" | "forbidden" | "invalid-state" | "invalid-notification" | "rate-limited", message: string) { super(message); } }
export class OfficialPaymentService {
  private orders = new Map<string, OfficialCheckoutOrder>(); private events = new Set<string>(); private counter = 0; private creation = new Map<string, number[]>();
  constructor(private readonly catalog: readonly BillingProduct[], private readonly billing: BillingService, private readonly providers: Record<PaymentChannel, OfficialPaymentProviderAdapter>) {}
  async create(userId: string, productId: string, channel: PaymentChannel, nowMs = Date.now()) { const attempts = (this.creation.get(userId) ?? []).filter(time => time > nowMs - 60_000); if (attempts.length >= 10) throw new OfficialPaymentError("rate-limited", "下单请求过于频繁"); this.creation.set(userId, [...attempts, nowMs]); const product = this.catalog.find(item => item.id === productId && item.published); if (!product) throw new OfficialPaymentError("not-found", "商品不存在"); const id = `official-order-${++this.counter}`; const action = await this.providers[channel].create({ orderId: id, amountCents: product.priceCents, currency: "CNY", description: product.displayName }); const order: OfficialCheckoutOrder = { id, userId, product: structuredClone(product), amountCents: product.priceCents, currency: "CNY", channel, status: "payment_pending", action, createdAtMs: nowMs, updatedAtMs: nowMs }; this.orders.set(id, order); return order; }
  userOrders(userId: string) { return [...this.orders.values()].filter(item => item.userId === userId); }
  orderForUser(userId: string, id: string) { const order = this.order(id); if (order.userId !== userId) throw new OfficialPaymentError("forbidden", "无权访问订单"); return order; }
  async handleNotification(channel: PaymentChannel, payload: unknown, nowMs = Date.now()) { const event = await this.providers[channel].verifyNotification(payload); if (!event.verified || !event.paid) throw new OfficialPaymentError("invalid-notification", "支付通知验证失败"); if (this.events.has(event.providerEventId)) return this.order(event.orderId); const order = this.order(event.orderId); if (order.channel !== channel || event.amountCents !== order.amountCents || event.currency !== order.currency) throw new OfficialPaymentError("invalid-notification", "支付通知与订单不匹配"); this.events.add(event.providerEventId); return this.markPaid(order, nowMs); }
  async query(userId: string, id: string, nowMs = Date.now()) { const order = this.orderForUser(userId, id); const state = await this.providers[order.channel].query(id); if (state === "paid") return this.markPaid(order, nowMs); if (state === "failed" || state === "closed") { const next = { ...order, status: state as "failed" | "closed", updatedAtMs: nowMs }; this.orders.set(id, next); return next; } return order; }
  async close(userId: string, id: string, nowMs = Date.now()) { const order = this.orderForUser(userId, id); if (order.status === "paid") throw new OfficialPaymentError("invalid-state", "已支付订单不能关闭"); await this.providers[order.channel].close(id); const next = { ...order, status: "closed" as const, updatedAtMs: nowMs }; this.orders.set(id, next); return next; }
  async refund(role: "support" | "refund-reviewer", id: string, nowMs = Date.now()) { if (role !== "refund-reviewer") throw new OfficialPaymentError("forbidden", "没有退款权限"); const order = this.order(id); if (order.status !== "paid") throw new OfficialPaymentError("invalid-state", "订单不能退款"); const state = await this.providers[order.channel].refund(id, order.amountCents); const next = { ...order, status: state === "refunded" ? "refunded" as const : state === "pending" ? "refund_pending" as const : "paid" as const, updatedAtMs: nowMs }; this.orders.set(id, next); return next; }
  private markPaid(order: OfficialCheckoutOrder, nowMs: number) { if (order.status === "paid") return order; const paid = { ...order, status: "paid" as const, updatedAtMs: nowMs }; this.orders.set(order.id, paid); this.billing.activateVerifiedProduct(order.userId, order.product, order.id, nowMs); return paid; }
  private order(id: string) { const value = this.orders.get(id); if (!value) throw new OfficialPaymentError("not-found", "订单不存在"); return value; }
}
