from __future__ import annotations

from typing import Mapping, Protocol


class BillingPersistencePort(Protocol):
    def ensure_welcome_grant(self, *, user_id: str, points: int, created_at_ms: int) -> None: ...
    def list_ledger(self, *, user_id: str) -> list[dict[str, object]]: ...
    def balance(self, *, user_id: str) -> int: ...
    def create_checkout_order(self, *, order: Mapping[str, object], idempotency_key: str) -> dict[str, object]: ...
    def replace_checkout_action(self, *, order_id: str, action: Mapping[str, object], updated_at_ms: int) -> dict[str, object]: ...
    def checkout_order(self, *, order_id: str) -> dict[str, object]: ...
    def list_checkout_orders(self, *, user_id: str) -> list[dict[str, object]]: ...
    def confirm_checkout_paid(self, *, order_id: str, amount_cents: int, provider_trade_no: str, paid_at_ms: int) -> dict[str, object]: ...
    def create_index_quote(self, *, quote: Mapping[str, object], idempotency_key: str) -> dict[str, object]: ...
    def index_quote(self, *, quote_id: str) -> dict[str, object]: ...
    def reserve_index_quote(self, *, quote_id: str, created_at_ms: int) -> dict[str, object]: ...
    def settle_index_quote(self, *, quote_id: str, reference_id: str, settled_at_ms: int) -> dict[str, object] | None: ...
    def release_index_quote(self, *, quote_id: str, released_at_ms: int) -> dict[str, object] | None: ...
    def list_entitlements(self, *, user_id: str) -> list[dict[str, object]]: ...

