from __future__ import annotations

from typing import Mapping, Protocol


class BillingPersistencePort(Protocol):
    def list_catalog_products(self) -> list[dict[str, object]]: ...
    def ensure_welcome_grant(self, *, user_id: str, points: int, created_at_ms: int) -> None: ...
    def list_ledger(self, *, user_id: str) -> list[dict[str, object]]: ...
    def balance(self, *, user_id: str) -> int: ...
    def get_or_create_referral_code(self, *, user_id: str, candidate_code: str, created_at_ms: int) -> str: ...
    def resolve_referral_code(self, *, referral_code: str) -> dict[str, object] | None: ...
    def referral_status(self, *, user_id: str) -> dict[str, object]: ...
    def activate_referral(self, *, invitee_user_id: str, referral_code: str, activated_at_ms: int) -> dict[str, object]: ...
    def growth_referral_settings(self) -> dict[str, object]: ...
    def update_growth_referral_settings(self, *, enabled: bool, reward_points: int, updated_by_user_id: str, updated_at_ms: int) -> dict[str, object]: ...
    def list_payment_channel_configs(self) -> list[dict[str, object]]: ...
    def payment_channel_config(self, *, channel: str) -> dict[str, object]: ...
    def save_payment_channel_config(self, *, channel: str, public_config: Mapping[str, object], secret_config_ciphertext: str | None, validation_status: str, validation_errors: list[str], updated_by_user_id: str, updated_at_ms: int) -> dict[str, object]: ...
    def set_payment_channel_enabled(self, *, channel: str, enabled: bool, updated_by_user_id: str, updated_at_ms: int) -> dict[str, object]: ...
    def create_checkout_order(self, *, order: Mapping[str, object], idempotency_key: str) -> dict[str, object]: ...
    def replace_checkout_action(self, *, order_id: str, action: Mapping[str, object], updated_at_ms: int) -> dict[str, object]: ...
    def checkout_order(self, *, order_id: str) -> dict[str, object]: ...
    def list_checkout_orders(self, *, user_id: str) -> list[dict[str, object]]: ...
    def confirm_checkout_paid(self, *, order_id: str, amount_cents: int, provider_trade_no: str, paid_at_ms: int) -> dict[str, object]: ...
    def create_index_quote(self, *, quote: Mapping[str, object], idempotency_key: str) -> dict[str, object]: ...
    def index_quote(self, *, quote_id: str) -> dict[str, object]: ...
    def reserve_index_quote(self, *, quote_id: str, created_at_ms: int) -> dict[str, object]: ...
    def settle_index_quote(self, *, quote_id: str, reference_id: str, settled_at_ms: int) -> dict[str, object] | None: ...
    def release_index_quote(self, *, quote_id: str, released_at_ms: int) -> dict[str, object] | None: ...
    def reserve_usage(self, *, usage: Mapping[str, object], created_at_ms: int) -> dict[str, object]: ...
    def settle_usage(self, *, usage_id: str, settled_at_ms: int) -> dict[str, object] | None: ...
    def release_usage(self, *, usage_id: str, released_at_ms: int) -> dict[str, object] | None: ...
    def release_stale_usage_reservations(self, *, stale_before_ms: int, released_at_ms: int, user_id: str | None = None) -> int: ...
    def list_entitlements(self, *, user_id: str) -> list[dict[str, object]]: ...
    def expire_checkout_orders(self, *, now_ms: int, user_id: str | None = None, order_id: str | None = None) -> int: ...
    def record_payment_callback(self, *, event: Mapping[str, object]) -> dict[str, object]: ...
    def complete_payment_callback(self, *, event_fingerprint: str, outcome: str, completed_at_ms: int, order_known: bool | None = None, amount_matches: bool | None = None) -> None: ...
    def create_reconciliation_issue(self, *, issue_type: str, event_fingerprint: str, order_id: str, detected_at_ms: int) -> None: ...
    def reconciliation_summary(self, *, now_ms: int) -> dict[str, object]: ...
