import { describe, expect, it } from "vitest";
import type { OfficialPaymentProviderAdapter } from "../src/official-payment-service.js";
import { OfficialPaymentService } from "../src/official-payment-service.js";
import { BillingService, defaultBillingProducts } from "../src/billing-service.js";
const provider = (): OfficialPaymentProviderAdapter => ({ create: async input => ({ kind: "dynamic_qr", value: `provider:${input.orderId}`, expiresAtMs: 100 }), query: async () => "pending", verifyNotification: async payload => payload as never, close: async () => undefined, refund: async () => "refunded" });
describe("OfficialPaymentService", () => {
  it("uses catalog price and activates a verified payment once", async () => { const billing = new BillingService(); const adapter = provider(); const service = new OfficialPaymentService(defaultBillingProducts, billing, { wechat: adapter, alipay: adapter }); const order = await service.create("u1", "points-300", "wechat", 1); expect(order.amountCents).toBe(3990); const event = { providerEventId: "event-1", orderId: order.id, merchantId: "merchant", applicationId: "app", amountCents: 3990, currency: "CNY" as const, paid: true, verified: true }; await service.handleNotification("wechat", event, 2); await service.handleNotification("wechat", event, 3); expect(billing.balance("u1")).toBe(300); });
  it("rejects wrong amount and wrong-user reads", async () => { const billing = new BillingService(); const adapter = provider(); const service = new OfficialPaymentService(defaultBillingProducts, billing, { wechat: adapter, alipay: adapter }); const order = await service.create("u1", "points-300", "wechat", 1); await expect(service.handleNotification("wechat", { providerEventId: "bad", orderId: order.id, merchantId: "m", applicationId: "a", amountCents: 1, currency: "CNY", paid: true, verified: true })).rejects.toMatchObject({ code: "invalid-notification" }); expect(() => service.orderForUser("u2", order.id)).toThrowError(expect.objectContaining({ code: "forbidden" })); });
  it("recovers via active query, closes pending orders and restricts refunds", async () => { const billing = new BillingService(); const paidProvider = { ...provider(), query: async () => "paid" as const }; const service = new OfficialPaymentService(defaultBillingProducts, billing, { wechat: paidProvider, alipay: paidProvider }); const order = await service.create("u1", "pass-3", "alipay", 1); expect((await service.query("u1", order.id, 2)).status).toBe("paid"); await expect(service.refund("support", order.id, 3)).rejects.toMatchObject({ code: "forbidden" }); expect((await service.refund("refund-reviewer", order.id, 4)).status).toBe("refunded"); });
});
