import React from 'react';
import {AbsoluteFill, Audio, Sequence, spring, staticFile, useCurrentFrame} from 'remotion';

const C = {bg:'#07111f', panel:'#102238', text:'#f4f8fb', muted:'#9fb0c2', mint:'#63e6be', cyan:'#62d8ff', line:'rgba(255,255,255,.14)'};
const shell: React.CSSProperties = {fontFamily:'Inter, Arial, sans-serif', background:`radial-gradient(circle at 80% 8%,rgba(31,143,130,.28),transparent 30%),${C.bg}`, color:C.text};

const Wordmark=({small=false}:{small?:boolean})=><div style={{fontWeight:900,letterSpacing:small?3:5,color:C.mint,fontSize:small?28:34}}>OFFERSTEADY</div>;
const Pill=({children}:{children:React.ReactNode})=><div style={{display:'inline-block',padding:'14px 22px',border:`1px solid ${C.line}`,borderRadius:999,color:C.mint,fontSize:26}}>{children}</div>;

const Hook=()=>{const f=useCurrentFrame();const p=spring({frame:f,fps:30,config:{damping:13,stiffness:150}});return <AbsoluteFill style={{...shell,alignItems:'center',justifyContent:'center',padding:70,textAlign:'center'}}><Wordmark/><div style={{fontSize:92,fontWeight:950,lineHeight:1.02,marginTop:40,transform:`translateY(${(1-p)*55}px)`,opacity:p}}>Walk into your<br/><span style={{color:C.mint}}>next interview</span><br/>prepared.</div><div style={{marginTop:42}}><Pill>AI interview copilot</Pill></div><div style={{position:'absolute',bottom:54,fontSize:24,color:C.muted}}>mianshiwen.cn</div></AbsoluteFill>};

const Features=()=>{const f=useCurrentFrame(); const cards=[['01','Your context','Bring the resume, job description and knowledge you need for this interview.'],['02','Real-time help','Use voice, typed questions or screenshots to organize your next answer.'],['03','Stay in control','Suggestions are checked by you. Your experience stays yours.']];return <AbsoluteFill style={{...shell,padding:'90px 62px'}}><Wordmark small/><div style={{fontSize:62,fontWeight:950,marginTop:42,lineHeight:1.05}}>Less scrambling.<br/><span style={{color:C.cyan}}>More clarity.</span></div><div style={{marginTop:54,display:'grid',gap:18}}>{cards.map((c,i)=>{const p=spring({frame:f-i*10,fps:30,config:{damping:14,stiffness:130}});return <div key={c[0]} style={{display:'grid',gridTemplateColumns:'82px 1fr',gap:18,background:'rgba(255,255,255,.055)',border:`1px solid ${C.line}`,borderRadius:26,padding:'24px 22px',opacity:Math.max(0,p),transform:`translateX(${(1-p)*80}px)`}}><div style={{fontSize:30,color:C.mint,fontWeight:900}}>{c[0]}</div><div><div style={{fontSize:35,fontWeight:900}}>{c[1]}</div><div style={{fontSize:25,lineHeight:1.35,color:C.muted,marginTop:7}}>{c[2]}</div></div></div>})}</div><div style={{position:'absolute',bottom:46,left:62,right:62,fontSize:23,color:C.muted}}>Designed for practice and permitted interview workflows.</div></AbsoluteFill>};

const CTA=()=>{const f=useCurrentFrame();const p=spring({frame:f,fps:30,config:{damping:12,stiffness:140}});return <AbsoluteFill style={{...shell,alignItems:'center',justifyContent:'center',padding:64,textAlign:'center'}}><div style={{transform:`scale(${.82+.18*p})`,opacity:p}}><Wordmark/><div style={{fontSize:76,fontWeight:950,lineHeight:1.05,marginTop:32}}>Prepare with<br/><span style={{color:C.mint}}>OfferSteady.</span></div><div style={{fontSize:30,color:C.muted,marginTop:28}}>Turn scattered materials into a clear next step.</div><div style={{marginTop:44,display:'inline-block',padding:'19px 32px',borderRadius:999,background:C.mint,color:C.bg,fontSize:31,fontWeight:900}}>Try it at mianshiwen.cn</div></div></AbsoluteFill>};

export const InternationalVideo:React.FC<{variant:'short'|'feature'|'trust';bgm:boolean}> = ({variant,bgm}) => {const dur=variant==='short'?450:variant==='feature'?600:900; const featureStart=variant==='short'?180:variant==='feature'?210:270; const ctaStart=variant==='short'?300:variant==='feature'?450:630; return <AbsoluteFill style={shell}>{bgm&&<Audio src={staticFile('audio/bgm.mp3')} volume={0.07}/>}<Sequence from={0} durationInFrames={featureStart}><Hook/></Sequence><Sequence from={featureStart} durationInFrames={ctaStart-featureStart}><Features/></Sequence><Sequence from={ctaStart} durationInFrames={dur-ctaStart}><CTA/></Sequence><Sequence from={0} durationInFrames={dur}><Audio src={staticFile('audio/transition-soft.mp3')} volume={0.16}/></Sequence></AbsoluteFill>};

const Device=({phone=false,children}:{phone?:boolean;children:React.ReactNode})=><div style={{width:phone?300:760,height:phone?560:430,border:`3px solid ${C.line}`,borderRadius:phone?38:24,background:'#0b1a2c',padding:18,boxShadow:'0 20px 60px rgba(0,0,0,.35)'}}><div style={{height:24,display:'flex',justifyContent:'space-between',color:C.muted,fontSize:16}}><span>{phone?'9:41':'● LIVE INTERVIEW'}</span><span>●</span></div>{children}</div>;
const InterviewScene=()=>{const f=useCurrentFrame(); const phase=Math.min(5,Math.floor(f/180)); const pop=(delay:number)=>spring({frame:f-delay,fps:30,config:{damping:14,stiffness:120}}); const q=phase<2?'Tell me about a challenge you solved.':phase<4?'What makes you a strong fit for this role?':'You have a clear next step.'; return <AbsoluteFill style={{...shell,padding:'58px 48px'}}><Wordmark small/><div style={{fontSize:50,fontWeight:900,marginTop:24}}>Your interview is live.<br/><span style={{color:C.mint}}>Support is ready.</span></div><div style={{marginTop:38,display:'flex',gap:24,alignItems:'center',justifyContent:'center'}}><Device><div style={{height:180,borderRadius:16,background:'linear-gradient(135deg,#254b68,#13283b)',display:'flex',alignItems:'center',justifyContent:'center',fontSize:38}}>INTERVIEWER</div><div style={{marginTop:18,fontSize:24,color:C.muted}}>Question</div><div style={{fontSize:27,fontWeight:800,marginTop:7}}>{q}</div><div style={{marginTop:24,display:'flex',gap:10}}><span style={{background:'#18364b',padding:'10px 15px',borderRadius:12,color:C.cyan}}>🎙 Mic on</span><span style={{background:'#18364b',padding:'10px 15px',borderRadius:12,color:C.mint}}>● Recording off</span></div></Device><div style={{fontSize:42,color:C.mint}}>→</div><Device phone><div style={{background:'#132b3c',borderRadius:18,padding:16,height:'100%'}}><div style={{fontSize:20,color:C.mint,fontWeight:800}}>OFFERSTEADY</div><div style={{marginTop:25,fontSize:20,color:C.muted}}>Live context</div><div style={{marginTop:10,fontSize:25,fontWeight:800}}>Key points</div><div style={{marginTop:20,background:'#1b3d4c',borderRadius:14,padding:15,fontSize:20,lineHeight:1.35,opacity:Math.max(.25,pop(40))}}>• Use a specific example<br/>• Explain your action<br/>• End with the result</div><div style={{marginTop:22,border:`1px solid ${C.mint}`,borderRadius:14,padding:13,textAlign:'center',color:C.mint,fontSize:20}}>Ready when you are</div></div></Device></div><div style={{position:'absolute',bottom:55,left:48,right:48,textAlign:'center',fontSize:27,color:C.muted}}>{phase===0?'One computer. One phone. One calm workflow.':phase===1?'See useful context without leaving the conversation.':phase===2?'Capture a question with one tap.':phase===3?'Check the same content on mobile.':'Stay focused on your own answer.'}</div></AbsoluteFill>};
const InterviewCTA=()=> <AbsoluteFill style={{...shell,alignItems:'center',justifyContent:'center',textAlign:'center',padding:60}}><Wordmark/><div style={{fontSize:78,fontWeight:950,lineHeight:1.04,marginTop:38}}>Interview with<br/><span style={{color:C.mint}}>more clarity.</span></div><div style={{fontSize:30,color:C.muted,marginTop:28,lineHeight:1.35}}>Prepare before the call.<br/>Stay supported when it matters.</div><div style={{marginTop:46,background:C.mint,color:C.bg,padding:'20px 34px',borderRadius:999,fontSize:30,fontWeight:900}}>Try OfferSteady · mianshiwen.cn</div></AbsoluteFill>;
export const InternationalInterviewVideo:React.FC<{bgm:boolean}> = ({bgm}) => <AbsoluteFill style={shell}>{bgm&&<Audio src={staticFile('audio/bgm.mp3')} volume={0.045}/>}<Audio src={staticFile('audio/offersteady-international-voice.mp3')} volume={0.92}/><Sequence from={0} durationInFrames={1620}><InterviewScene/></Sequence><Sequence from={1620} durationInFrames={180}><InterviewCTA/></Sequence><Sequence from={0} durationInFrames={1800}><Audio src={staticFile('audio/transition-soft.mp3')} volume={0.14}/></Sequence></AbsoluteFill>;
